const products = [
  {
    id: 1,
    name: "Cognirich Neuro-Protector Tablets",
    category: "Tablets",
    price: 150,
    image: "images/aspirin.jpg",
  },
  {
    id: 2,
    name: "Cognirich Clears Ringing Tablets",
    category: "Tablets",
    price: 200,
    image: "images/vitamin-c.jpg",
  },
  {
    id: 3,
    name: "Pnerve Injection",
    category: "Injections",
    price: 350,
    image: "images/pnerve_injection.jpeg",
  },
  {
    id: 4,
    name: "Cognirich-BT Tablets",
    category: "Tablets",
    price: 120,
    image: "images/cough-syrup.jpg",
  },
  {
    id: 5,
    name: "Pnerve-OD Capsules",
    category: "Injections",
    price: 600,
    image: "images/insulin.jpg",
  },
  {
    id: 6,
    name: "Pnerve Tablets",
    category: "Tablets",
    price: 250,
    image: "images/multivitamin.jpg",
  },
   {
    id: 7,
    name: "Pnerve liniment",
    category: "Lotions",
    price: 250,
    image: "images/multivitamin.jpg",
  },
 {
    id: 8,
    name: "Palsinorm Capsules",
    category: "Tablets",
    price: 250,
    image: "images/multivitamin.jpg",
  },
 {
    id: 9,
    name: "Chillban-FM Tablets",
    category: "Tablets",
    price: 250,
    image: "images/multivitamin.jpg",
  },
{
    id: 10,
    name: "Chillban-P Tablets",
    category: "Tablets",
    price: 250,
    image: "images/multivitamin.jpg",
  },

  {
    id: 11,
    name: "Chillban Rub Oil",
    category: "Lotions",
    price: 250,
    image: "images/Chillban_rub_oil.jpeg",
  },
 {
    id: 12,
    name: "Chillban-LS Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
   {
    id: 13,
    name: "Cognirich Syrup",
    category: "Syrups",
    price: 250,
    image: "images/cognirich_syrup.jpeg",
  },

 {
    id: 14,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 15,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 16,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 17,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 18,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 19,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 20,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 21,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },
  {
    id: 22,
    name: "Chillban-A Syrup",
    category: "Syrups",
    price: 250,
    image: "images/multivitamin.jpg",
  },

];
